/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#0F2942',
        'primary-deep': '#111A31',
        secondary: '#007D5B',
        'secondary-accent': '#10b981',
        tertiary: '#2563EB',
        neutral: {
          50: '#F6F7F8',
          0: '#FFFFFF',
        },
        focus: '#D97706',
        ink: '#191c1e',
        muted: '#45464d',
        border: '#e2e8f0',
        'surface-muted': '#F0F2F4',
        'secondary-container': '#82F5C1',
        'pale-mint': '#D9FAEC',
        'soft-border': '#e2e8f0',
        'soft-gray': '#94a3b8',
        'toggle-off': '#D7DBE0',
        selected: '#000000',
        white: '#FFFFFF',
        'status-pos-bg': '#ecfdf5',
        'status-pos-border': '#059669',
        'status-pos-text': '#065f46',
        'status-neg-bg': '#f1f5f9',
        'status-neg-border': '#64748b',
        'status-neg-text': '#334155',
        'map-surface': '#DBE5DD',
        'map-border': '#B9C8BD',
        'map-label': '#66716B',
        'status-gray': '#e8e9eb',
        'match-surface': '#EDF0F2',
      },
      spacing: {
        0: '0px',
        1: '8px',
        2: '16px',
        3: '24px',
        4: '32px',
        5: '40px',
        6: '48px',
        7: '56px',
        8: '64px',
        screen: '16px',
        'touch-min': '48px',
      },
      minHeight: {
        touch: '48px',
      },
      minWidth: {
        touch: '48px',
      },
      fontFamily: {
        sans: ['Atkinson Hyperlegible Next', 'Atkinson Hyperlegible', 'system-ui', 'sans-serif'],
        display: ['Atkinson Hyperlegible Next', 'Atkinson Hyperlegible', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-xl-mobile': ['26px', { lineHeight: '34px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '24px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '18px', fontWeight: '700' }],
        'display-lg': ['38px', { lineHeight: '46px', fontWeight: '800' }],
        'display-md': ['26px', { lineHeight: '32px', fontWeight: '800' }],
        'icon-xl': ['32px', { lineHeight: '36px', fontWeight: '700' }],
        'icon-lg': ['28px', { lineHeight: '32px', fontWeight: '700' }],
        'icon-md': ['24px', { lineHeight: '28px', fontWeight: '700' }],
        'icon-sm': ['22px', { lineHeight: '26px', fontWeight: '700' }],
        'body-xl': ['21px', { lineHeight: '29px', fontWeight: '400' }],
        'body-md-tight': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'label-xs': ['11px', { lineHeight: '16px', fontWeight: '700' }],
      },
      borderRadius: {
        control: '8px',
        panel: '16px',
      },
    },
  },
  plugins: [],
};
