/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: '#2445FF',
        'primary-deep': '#1029C9',
        secondary: '#00805B',
        'secondary-accent': '#10b981',
        tertiary: '#2563EB',
        neutral: {
          50: '#F7F8FF',
          0: '#FFFFFF',
        },
        focus: '#D97706',
        ink: '#101B35',
        muted: '#55617B',
        border: '#e2e8f0',
        'surface-muted': '#EEF2FF',
        'secondary-container': '#D8FAEF',
        'pale-mint': '#E9FFF7',
        'soft-border': '#e2e8f0',
        'soft-gray': '#94a3b8',
        'toggle-off': '#D7DBE0',
        selected: '#2445FF',
        white: '#FFFFFF',
        'status-pos-bg': '#ecfdf5',
        'status-pos-border': '#059669',
        'status-pos-text': '#065f46',
        'status-neg-bg': '#f1f5f9',
        'status-neg-border': '#64748b',
        'status-neg-text': '#334155',
        'map-surface': '#E8EEF9',
        'map-border': '#CBD5E1',
        'map-label': '#475569',
        'status-gray': '#e8e9eb',
        'match-surface': '#EDF0F2',
        'login-border': '#e2e8f0',
        'mat-primary': '#0028d2',
        'mat-on-primary': '#ffffff',
        'mat-primary-container': '#1e40ff',
        'mat-on-primary-container': '#d2d5ff',
        'mat-primary-fixed': '#dfe0ff',
        'mat-primary-fixed-dim': '#bcc3ff',
        'mat-on-primary-fixed': '#000d60',
        'mat-on-primary-fixed-variant': '#0028d3',
        'mat-inverse-primary': '#bcc3ff',
        'mat-secondary': '#565e74',
        'mat-on-secondary': '#ffffff',
        'mat-secondary-container': '#dae2fd',
        'mat-on-secondary-container': '#5c647a',
        'mat-secondary-fixed': '#dae2fd',
        'mat-secondary-fixed-dim': '#bec6e0',
        'mat-on-secondary-fixed': '#131b2e',
        'mat-on-secondary-fixed-variant': '#3f465c',
        'mat-tertiary': '#005136',
        'mat-on-tertiary': '#ffffff',
        'mat-tertiary-container': '#006c49',
        'mat-on-tertiary-container': '#63f1b4',
        'mat-tertiary-fixed': '#6ffbbe',
        'mat-tertiary-fixed-dim': '#4edea3',
        'mat-on-tertiary-fixed': '#002113',
        'mat-on-tertiary-fixed-variant': '#005236',
        'mat-error': '#ba1a1a',
        'mat-on-error': '#ffffff',
        'mat-error-container': '#ffdad6',
        'mat-on-error-container': '#93000a',
        'mat-background': '#f8f9ff',
        'mat-on-background': '#0b1c30',
        'mat-surface': '#f8f9ff',
        'mat-surface-dim': '#cbdbf5',
        'mat-surface-bright': '#f8f9ff',
        'mat-surface-container-lowest': '#ffffff',
        'mat-surface-container-low': '#eff4ff',
        'mat-surface-container': '#e5eeff',
        'mat-surface-container-high': '#dce9ff',
        'mat-surface-container-highest': '#d3e4fe',
        'mat-on-surface': '#0b1c30',
        'mat-on-surface-variant': '#444657',
        'mat-surface-variant': '#d3e4fe',
        'mat-surface-tint': '#1f41ff',
        'mat-inverse-surface': '#213145',
        'mat-inverse-on-surface': '#eaf1ff',
        'mat-outline': '#747689',
        'mat-outline-variant': '#c4c5da',
      },
      spacing: {
        0: '0px',
        1: '8px',
        2: '16px',
        3: '24px',
        4: '32px',
        5: '40px',
        6: '48px',
        7: '56px',
        8: '64px',
        screen: '16px',
        'touch-min': '48px',
      },
      minHeight: {
        touch: '48px',
      },
      minWidth: {
        touch: '48px',
      },
      fontFamily: {
        sans: ['Atkinson Hyperlegible Next', 'Atkinson Hyperlegible', 'system-ui', 'sans-serif'],
        display: ['Atkinson Hyperlegible Next', 'Atkinson Hyperlegible', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['32px', { lineHeight: '40px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-xl-mobile': ['26px', { lineHeight: '34px', fontWeight: '700', letterSpacing: '-0.01em' }],
        'headline-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'label-lg': ['16px', { lineHeight: '24px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '18px', fontWeight: '700' }],
        'display-lg': ['38px', { lineHeight: '46px', fontWeight: '800' }],
        'display-md': ['26px', { lineHeight: '32px', fontWeight: '800' }],
        'icon-xl': ['32px', { lineHeight: '36px', fontWeight: '700' }],
        'icon-lg': ['28px', { lineHeight: '32px', fontWeight: '700' }],
        'icon-md': ['24px', { lineHeight: '28px', fontWeight: '700' }],
        'icon-sm': ['22px', { lineHeight: '26px', fontWeight: '700' }],
        'body-xl': ['21px', { lineHeight: '29px', fontWeight: '400' }],
        'body-md-tight': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'label-xs': ['11px', { lineHeight: '16px', fontWeight: '700' }],
      },
      borderRadius: {
        control: '8px',
        panel: '16px',
      },
    },
  },
  plugins: [],
};
